<?php

use Drupal\user\UserInterface;
use Drupal\views\ViewExecutable;


/**
 * Implements hook_user_login().
 *
 * @param \Drupal\user\UserInterface $account
 */
function favoritos_user_login(UserInterface $account) {
  \Drupal::service('favoritos')->addUsuarioFavorito($account);
}

/**
 * Implements hook_theme().
 */
function favoritos_theme($existing, $type, $theme, $path) {
  return [
    'link_favorito' => [
      'template' => 'link-favorito',
      'variables' => ['commerce_product' => NULL, 'action' => NULL]
    ],
  ];
}


function template_preprocess_link_favorito(&$variables) {
  $route = Drupal::routeMatch();
  $query = [];
  if ($route) {
    if ($route->getRouteName() == 'view.favoritos.page') {
      $query['view'] ='page';
    }
    elseif ($route->getRouteName() == 'commerce_cart.page') {
      $query['view'] ='block';
    }
  }

  if (\Drupal::request()->query->get('view')) {
    $query['view'] =\Drupal::request()->query->get('view');
  }
  $product = $variables['commerce_product'];
  $variables['action'] = NULL;
  if ($product instanceof \Drupal\commerce_product\Entity\Product) {
    if (\Drupal::service('favoritos')->checkExistFavorito($product)) {
      $variables['action'] = \Drupal\Core\Link::createFromRoute('Favorito', 'favorito.action', ['commerce_product' => $product->id(), 'action' => 'delete'], ['attributes' => ['class' => 'use-ajax delete'], 'query' => $query]);
    }
    else {
      $variables['action'] = \Drupal\Core\Link::createFromRoute('Favorito', 'favorito.action', ['commerce_product' => $product->id(), 'action' => 'add'], ['attributes' => ['class' => 'use-ajax add'], 'query' => $query]);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param $variables
 */
function favoritos_preprocess_commerce_product(&$variables) {
  $variables['link_favorito'] = ['#theme' => 'link_favorito', '#commerce_product' => $variables["product_entity"]];
}

/**
 * Implements hook_views_pre_view().
 *
 * @param \Drupal\views\ViewExecutable $view
 * @param $display_id
 * @param array $args
 */
function favoritos_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'favoritos') {
    if (\Drupal::currentUser()->id()) {
      $args[1] = 'all';
    }
    elseif(isset($_COOKIE['wishlist'])) {
      $args[0] = 'all';
      $args[1] = $_COOKIE['wishlist'];
    }
  }
}
